### ISSUE TITLE
json.decoder Error Using PyLooker

### ISSUE THREAD

**Issue by cgnetsec** [bufferapp/pylooker#4]
Hello, 

I have been using pylooker in my script to run some looks and import them into google sheets. I seem to be running into this error:
`json.decoder.JSONDecodeError: Expecting Value: line 1, column 1 (char 0)`
every time I try to run something as simple as:
`def main():`     
`     api_endpoint = 'https://website.looker.com:19999/api/3.0/'`
`     lc = LookerClient(api_endpoint, auth_info.client_id, auth_info.client_secret)`
`     look_number = 999 `
`     look_data = lc.run_look(look_number, 'csv')`

Any help would be appreciated!

**Comment by davidgasquez** [comment]
Hey there @cgnetsec! I remember seeing this when the endpoint is not available. Would you mind giving a try to `api_endpoint = 'https://looker.website.com:19999/api/3.0/'` instead of `https://website.looker.com:19999/api/3.0/`?

**Comment by cgnetsec** [comment]
I went ahead and changed  `api_endpoint = 'https://website.looker.com:19999/api/3.0/'` to `https://looker.website.com:19999/api/3.0` however now I am receiving this error when I try to run the look:
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='looker.website.com', port=19999): Max retries exceeded with url: /api/3.0/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f2ef6d8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))`

**Comment by davidgasquez** [comment]
Interesting... Not really sure what's happening there. One thing we can try is running each step in isolation and check where it's failing. The [`client` code](https://github.com/bufferapp/pylooker/blob/master/pylooker/client.py) is really simple.

First, we get the headers for the requests:
```python
import requests
token_request = requests.post(
            url=api_endpoint+'login',
            data={
                'client_id': client_id,
                'client_secret': client_secret
            }
        )
token = token_request.json()['access_token']
headers = {'Authorization': 'token ' + token}
```

Once we have the headers, we can use them:
```python
response = requests.get(
            url='{}{}/run/{}?limit={}&apply_formatting={}&apply_vis={}&cache={}'.format(
                self.api_endpoint + 'looks/',
                look_id,
                format,
                limit
            ),
            headers=headers
        )
```
Something like that should work to get you started with a simple `response`. You can explore `response` even further and [check its attributes](http://docs.python-requests.org/en/master/api/#requests.Response). 

Let me know if you get stuck with anything! Happy to help debugging this one. :blush:
