### ISSUE TITLE
allow looker API to make unverified https requests 

### ISSUE THREAD

**Issue by vlouvet** [bufferapp/pylooker#5]
It would be great to have the option to make unverified https requests to our looker instance for those of us that have self hosted Looker instances behind self-signed SSL certificates.

I have hard coded the changes into client.py, seen in my attachment - although I don't think this is the right approach. Ideally, the library would have a config option set when defining the client which specifies whether or not to allow unverified SSL. 

For more guidance, please see the sdk_setup.rb file fromt he Ruby implementation of the Looker API located here: https://github.com/looker/looker-sdk-ruby/blob/master/examples/sdk_setup.rb

**Comment by davidgasquez** [comment]
Hey there! I've made some changes and now is possible to do non-signed requests!

Doing so is as easy as creating the client with verify false:

```python
lc = LookerClient(api_endpoint, client_id, client_secret, verify=False)
```

If you want to get this update, you can now update the package doing `pip install pylooker`. 

Closing the issue for now but let me know if you encounter some bugs!
